### PR TITLE
Improvements/support concurrency in mavend

### PR DESCRIPTION
**Pull request by ishantagarwal-x213235**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by eysi09** [comment]
Is this still applicable? cc @thsig

**Comment by ishantagarwal-x213235** [comment]
> Is this still applicable? cc @thsig

mavend is not fully working with heavy builds upto 0.8 version so i did not merge it.

**Comment by vvagaytsev** [comment]
Thanks for your contribution @ishantagarwal-x213235! I'll merge this to a branch and will continue working on this.

**Review by vvagaytsev — APPROVED** [review]

**Comment by vvagaytsev** [comment]
Superseded by #4695.

**Pull request merged**
