### PR TITLE
(docs) Update how-garden-works.md WIP

### PR DESCRIPTION
**Pull request by SmritiSatyan**
Improves readability (documentation PR)

### CODE REVIEW

**Comment by SmritiSatyan** [comment]
@edvald, @thsig -> requesting your review

**Comment by SmritiSatyan** [comment]
@eysi09 Hi, Can I get some insights on how to fix the build errors? I followed the installation steps, but not sure how to view the generated docs. Thanks!

**Comment by worldofgeese** [comment]
@SmritiSatyan thank you for the PR. Reading through the changes, I can't agree that it improves readability. The changes you've made _rephrase_ without substantively improving clarity of messaging. If you're interested in contributing to Garden, I urge you to first get deeply familiar with how Garden works technically and involve yourself with our community. PRs that improve grammar alone, though welcome, need to substantively improve messaging before I'd consider them.

**Comment by SmritiSatyan** [comment]
@worldofgeese Thank you for the response, this is work in progress. Its not complete, and I completely agree with what you say in terms of improving readability. I was curious to know where I am going wrong on the build errors.

**Comment by worldofgeese** [comment]
@SmritiSatyan can you please post your build errors in full so I can take a look?

**Comment by SmritiSatyan** [comment]
@worldofgeese  I can't see the stack since you closed the PR. Could you please re-open it?

**Comment by SmritiSatyan** [comment]
1. check-docs build error:
generated docs are not up-to-date! run \"yarn build && yarn generate-docs\" and commit the changes\n
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

2. test-framework

3. test-plugins

**Comment by worldofgeese** [comment]
@Walther as I'm on vacation, can you take this?

**Comment by Walther** [comment]
Hello @SmritiSatyan! The reasons for the failures are as follows:
- `test-plugins` fails because as an external contributor, you do not have access to our build secrets. This is expected - although we could internally improve this a bit by skipping the `pulumi` tests for external PRs.
- `test-framework` seems to have been a temporary failure, which resolved itself with a simple `Re-run workflow from failed`
- `check-docs` fails because you have changed the title of the document, and the change would also need to be reflected in `docs/README.md` as part of the Table of Contents listing. Running `yarn generate-docs` in your branch would generate the change for you.

That being said, unfortunately I agree with @worldofgeese above - as it currently stands, we don't see this PR as something that would be merged.

**Comment by SmritiSatyan** [comment]
I am still working on it, as the title suggests, it is a WIP. Can I please complete it? I have a lot more to write on it. It is not complete yet. Can you please reopen it?

**Comment by 10ko** [comment]
Hi @SmritiSatyan, thanks for your contribution!
I think what @Walther and @worldofgeese struggled with was the reasoning behind the PR: readability is a bit of a fuzzy and personal concept and there was not so much explanation on why you think those changes improved the text.

At the same time I also really appreciate the time you are putting into this and I'd like to find a way to better collaborate and scope your contributions. We have a lot of work planned around improving the docs (see #3961) and I can imagine we could either assign or share some of these chunks of improvements.

Why don't you join our [Discord server](https://discord.com/invite/FrmhuUjFs6)? All the folks from the project are in the #dev channel and I am sure everyone will be happy to discuss how best to contribute to the repo/docs.

Alternatively, if you are not into Discord, I'd suggest you to first open an issue where we can asynchronously discuss what improvements you'd like to make, scope them down and use it to track progress.

I really hope to see you on Discord, though! :)

💚, @10ko

**Comment by SmritiSatyan** [comment]
Hi @10ko , thank you for the elaborate response. I shall create an issue, and add my reasoning behind creating this PR. I am on the Discord server :)
Thanks.

**Pull request closed without merging**
