### PR TITLE
docs: link specifically to edge version

### PR DESCRIPTION
**Pull request by ellenkorbes**
I always find it a bit of a hassle to find the specific link to the Edge version of Docker, so I thought I'd use it in the documentation instead of the generic Docker For Windows one.

### CODE REVIEW

**Comment by drubin** [comment]
@ellenkorbes Minor issue, your commit should be `docs:`  since the changelog is auto-generated from this. 

ref https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type

**Comment by ellenkorbes** [comment]
Fixed. Thanks @drubin.

**Comment by drubin** [comment]
@ellenkorbes Maybe we need to make it more clear you need the edge version only the URL contains edge and I not sure people will notice their versions are different from edge?

**Comment by ellenkorbes** [comment]
The text immediately preceding this link is 

> Docker - We strongly recommend using the _Edge version_

so IMO we're fine in that regard.

**Pull request merged**
