### PR TITLE
SGV2: fixed single test for build command

### PR DESCRIPTION
**Pull request by vvagaytsev**
**What this PR does / why we need it**:
Fixed assertions for module versions.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Orzelius — COMMENTED** [review]
why not just get the builds from the graph and then use the `moduleVersion` method? This seems kinda hacky for no reason

**Comment by vvagaytsev** [comment]
> why not just get the builds from the graph and then use the `moduleVersion` method? This seems kinda hacky for no reason

Good point, thanks! Simplified the code in https://github.com/garden-io/garden/pull/3345/commits/f5247f830bbcd24c110f321ad8501e82cceaa507

**Review by Orzelius — APPROVED** [review]
Not quite what I meant but this works as well :smiley:

**Comment by vvagaytsev** [comment]
> Not quite what I meant but this works as well 😃

And what did you mean? In-place comments in the code could be more helpful to understand the intent :) If there is a better way to do that, let's just do it!

**Comment by Orzelius** [comment]
> And what did you mean? In-place comments in the code could be more helpful to understand the intent :) If there is a better way to do that, let's just do it!

It's my bad, I took a closer look and now realize this is the way to go. At first I thought why not just get the actions and modules from the graph and compare the versions, but I now realize that would not test the task output results.

**Pull request merged**
