### PR TITLE
fix(container): update Ingress API version

### LINKED ISSUE #2384: Deprecated apiVersion on generated Ingress resources
## Bug

I'm unable to start any services with ingress specified. Garden will receive the trying to run deploy the project in minikube. The same project was working on older garden versions. 

### Current Behavior
`garden dev`

```
Command "/home/aloise/.garden/tools/kubectl/11ac0bbd21058c50/kubectl --context=minikube --namespace=easyrentals-default apply --prune --selector service=gateway --output=json -f -" failed with code 1:

Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": an error on the server ("") has prevented the request from succeeding

Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": an error on the server ("") has prevented the request from succeeding
```

### Expected behavior

It was running on older garden + k8s versions.

### Reproducible example

Any project which has ingress is failing.

### Your environment

* **OS:** Arch Linux, 5.12.1
* minikube v1.19.1 + k8s v1.20.2
* garden v0.12.21

### PR DESCRIPTION
**Pull request by thsig**
**What this PR does / why we need it**:

Updated the API version of the `Ingress` resource generated for `container` module services.

**Which issue(s) this PR fixes**:

Fixes #2384.

### CODE REVIEW

**Comment by thsig** [comment]
@eysi09: Could you have a look at this one?

**Comment by twelvemo** [comment]
Why did you want to update to `networking.k8s.io/v1beta1` @thsig ? 
`networking.k8s.io/v1beta1` and `extensions/v1beta1` will both be deprecated in kubernetes 1.22
The future is in `networking.k8s.io/v1` but that is only available since kubernetes 1.19 and that would be a breaking change for some users.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

**Comment by thsig** [comment]
Ah, I see. Shall we hold off on this one for now, then?

**Comment by edvald** [comment]
@thsig I'm gonna close this and approach it a little differently in a separate PR

**Pull request closed without merging**
