### PR TITLE
chore(tooling): add a shell.nix file

### PR DESCRIPTION
**Pull request by mattpolzin**
**What this PR does / why we need it**:

Tangential to conversation I've seen in existing GitHub Issues about packaging Garden for Nixpkgs, this PR sets up a nix-shell file to support complete developer environment setup via the `nix-shell` command.

This may not even be a desirable addition to the Garden repo, but I was writing the shell file for myself anyway, so I figured I'd see if you all wanted it upstream.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by mattpolzin** [comment]
I noticed there's a PR open in draft right now to move from NodeJS `22.2.0` to NodeJS `22.5.1` within the `build-pkg.ts` file. Is it intentional that developing Garden uses NodeJS `18` (per `.tool-versions`) and packaging it uses NodeJS `22` or should I go ahead and bump the `.tool-versions` entry to `22`?

**Comment by stefreak** [comment]
@mattpolzin I also noticed this inconsistency and didn't get around to fix it yet! Feel free to change, it was not on purpose 👍

**Review by stefreak — APPROVED** [review]
This is amazing! Thank you for adding the `shell.nix`. Super happy to upstream it. Feel free to add the corrected `.tool-versions` in another commit.

**Comment by mattpolzin** [comment]
> Feel free to add the corrected .tool-versions in another commit.

Done.

**Review by stefreak — APPROVED** [review]
Thank you ❤️

**Pull request merged**
