### PR TITLE
chore: update `google-cloud/kms` in `core` package as well

### PR DESCRIPTION
**Pull request by Walther**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/garden-io/garden/security/dependabot/868

**Special notes for your reviewer**:

Updated @google-cloud/kms at the root package.json in previous PR https://github.com/garden-io/garden/pull/4862
Forgot to update it in `core` as well.

### CODE REVIEW

**Comment by shumailxyz** [comment]
@Walther some CI failures. May be give it a retry and see if it goes through.

**Comment by vvagaytsev** [comment]
> @Walther some CI failures. May be give it a retry and see if it goes through.

Those look known or caused by some network issues (at least in `e2e-jib-container` and `test-plugins`)

**Review by shumailxyz — APPROVED** [review]
Thank you for updating 💯

**Comment by shumailxyz** [comment]
Just retried the CI again. let's see if test-plugins passes

**Review by vvagaytsev — APPROVED** [review]

**Pull request merged**
