### PR TITLE
chore(docker): upgrade node version in alpine and buster

### PR DESCRIPTION
**Pull request by solomonope**
**What this PR does / why we need it**:
This PR upgrades the version of Nodejs in use in the alpine and buster docker images.

Node version 12.18.3, is the minimum node version that supports CLS, Garden Enterprise runs an image that is based on Gardendev images.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by thsig** [comment]
Looks good to me, but the `build-docker-aws-gcloud`, `build-docker-azure` and `build-docker-aws` steps are failing here.

**Comment by edvald** [comment]
I suspect the switch between alpine versions is the cause for the problem. Is there any particular reason to do that?

**Comment by edvald** [comment]
Another potential issue is that it's the Node.js version that _pkg_ uses that needs to be updated. I'm not quite sure if this particular version is available there.

**Comment by solomonope** [comment]
> Looks good to me, but the `build-docker-aws-gcloud`, `build-docker-azure` and `build-docker-aws` steps are failing here.

I would check it

**Comment by solomonope** [comment]
> I suspect the switch between alpine versions is the cause for the problem. Is there any particular reason to do that?

There is no specific reason for upgrading the alpine version, I would look for a lower alpine version that works

**Review by thsig — APPROVED** [review]

**Pull request merged**
