### PR TITLE
chore: tag packages with version 0.13.0-development

### PR DESCRIPTION
**Pull request by Walther**
**What this PR does / why we need it**:

Currently, it is difficult to distinguish between two `garden` binaries or containers, as `garden version` will return `0.12.x`.
With this PR, any binary or container built from the 0.13 branch will report the correct version string.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Because `0.13.0-development` is a pre-release, we need to explicitly depend on the pre-release versions in all of our internal dependencies - otherwise `yarn` will not find the packages in the workspace. We should revert this back to the `"*"` version before merging to `main`.

### CODE REVIEW

**Review by vvagaytsev — CHANGES_REQUESTED** [review]
Looks good! Please check the [CI check-docs step](https://app.circleci.com/pipelines/github/garden-io/garden/15850/workflows/0977366c-9d30-45a7-9187-4b01c5dd5570/jobs/264751).

It fails saying "generated docs are not up-to-date!".

**Comment by vvagaytsev** [comment]
@Walther can we just use `0.13` as a version? Then links will work because we do have `0.13` branch.

**Comment by Walther** [comment]
Unfortunately that won't work either, as `0.13` is an invalid version for `yarn` (and we cannot use `0.13.0` either as we don't have a tagged release for that).

I'm thinking maybe we should just drop this PR, the 0.13 branch is temporary anyway and we are getting closer and closer to release.

**Comment by vvagaytsev** [comment]
Ok, let's just drop this.

**Pull request closed without merging**
