### PR TITLE
Fix typo in docs from "containes" to "contains"

### PR DESCRIPTION
**Pull request by vrybas**
Fix typo in docs from "containes" to "contains"

**What this PR does / why we need it**:

Fixes the typo in docs.

**Which issue(s) this PR fixes**:

No issue exist for this change

**Special notes for your reviewer**:

none

### CODE REVIEW

**Comment by vrybas** [comment]
Hello everyone. Trying to use Garden to setup the development environment on the local k8s cluster. Just noticed the typo and decided to fix. Cheers!

**Comment by eysi09** [comment]
Hi @vrybas and thanks for the PR! 

Just noticed you're closing it, but we'd be very happy to receive this fix. I think CI is failing though because the auto-generated docs are out of date. You can re-generate them with `yarn run generate-docs`.

**Comment by vrybas** [comment]
Hey @eysi09, I can't get through the pre-commit hooks. 
I've removed the trailing space change from `docs/reference/commands.md ` and trying to push.  
My current problem is I run `yarn run generate-docs` and it succeeds, but pre-commit hook `yarn run check-docs` fails and does not allow me to push.

```
➜  garden git:(fix-docs-typo-f18f32a) yarn run generate-docs
yarn run v1.22.5
$ ./scripts/run-script.ts generate-docs

Running script generate-docs in package(s) @garden-io/cli, @garden-io/core, @garden-io/dashboard, @garden-io/garden-conftest-container, @garden-io/garden-conftest-kubernetes, @garden-io/garden-conftest, @garden-io/sdk
┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
$ node ./build/src/generate-docs.js                                                                                                                                         ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  Updating command references...                                                                                                                                              ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  Updating config references...                                                                                                                                               ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/providers/conftest.md                                                                                          ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/providers/conftest-container.md                                                                                ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/providers/conftest-kubernetes.md                                                                               ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/module-types/exec.md                                                                                           ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/module-types/container.md                                                                                      ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/module-types/conftest.md                                                                                       ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/module-types/hadolint.md                                                                                       ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/module-types/helm.md                                                                                           ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/module-types/kubernetes.md                                                                                     ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/module-types/maven-container.md                                                                                ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/module-types/openfaas.md                                                                                       ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/module-types/persistentvolumeclaim.md                                                                          ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/module-types/terraform.md                                                                                      ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  -> /Users/vrybas/Projects/github/forks/garden/docs/reference/config.md                                                                                                      ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  Updating template string reference...                                                                                                                                       ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  Generating table of contents...                                                                                                                                             ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  Table of contents generated successfuly.                                                                                                                                    ┄┄
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  Done!                                                                                                                                                                       ┄┄
┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
Done!

✨  Done in 7.51s.
```


```
➜  garden git:(fix-docs-typo-f18f32a) yarn run check-docs
yarn run v1.22.5
$ ./scripts/check-docs.sh
Academic tradition requires you to cite works you base your article on.
If you use programs that use GNU Parallel to process data for an article in a
scientific publication, please cite:

  Tange, O. (2020, July 22). GNU Parallel 20200722 ('Privacy Shield').
  Zenodo. https://doi.org/10.5281/zenodo.3956817

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

More about funding GNU Parallel and the citation notice:
https://www.gnu.org/software/parallel/parallel_design.html#Citation-notice

To silence this citation notice: run 'parallel --citation' once.

docs/using-garden/variables-and-templating.md
  276:179-276:251  warning  Link to unknown file: `(../reference/config.md`. Did you mean `../reference/config.md`  missing-file             remark-validate-links
  276:179-276:251  warning  Link to unknown heading in `(../reference/config.md`: `environmentsvarfile)`            missing-heading-in-file  remark-validate-links

⚠ 2 warnings
parallel: This job failed:
check_relative_links docs/misc/troubleshooting.md docs/misc/faq.md docs/misc/README.md docs/misc/telemetry.md docs/basics/how-garden-works.md docs/basics/stack-graph.md docs/basics/README.md docs/advanced/cert-manager-integration.md docs/advanced/README.md docs/advanced/terraform.md docs/advanced/using-remote-sources.md docs/using-garden/workflows.md docs/using-garden/modules.md docs/using-garden/tests.md docs/using-garden/projects.md docs/using-garden/configuration-overview.md docs/using-garden/README.md docs/using-garden/tasks.md docs/using-garden/variables-and-templating.md docs/using-garden/services.md docs/using-garden/using-the-cli.md docs/welcome.md docs/README.md docs/getting-started/3-connect-to-a-cluster.md docs/getting-started/1-installation.md docs/getting-started/2-initialize-a-project.md docs/getting-started/4-deploy-and-test.md docs/getting-started/README.md docs/getting-started/5-configure-your-project.md docs/getting-started/0-introduction.md docs/guides/cloud-provider-setup.md docs/guides/local-kubernetes.md docs/guides/hot-reload.md docs/guides/container-modules.md docs/guides/README.md docs/guides/remote-kubernetes.md docs/guides/using-garden-in-ci.md docs/guides/in-cluster-building.md docs/guides/using-helm-charts.md docs/reference/commands.md docs/reference/glossary.md docs/reference/providers/octant.md docs/reference/providers/kubernetes.md docs/reference/providers/openfaas.md docs/reference/providers/container.md docs/reference/providers/maven-container.md docs/reference/providers/local-kubernetes.md docs/reference/providers/hadolint.md docs/reference/providers/README.md docs/reference/providers/terraform.md docs/reference/providers/conftest.md docs/reference/providers/conftest-container.md docs/reference/providers/exec.md docs/reference/providers/conftest-kubernetes.md docs/reference/README.md docs/reference/config.md docs/reference/module-types/kubernetes.md docs/reference/module-types/openfaas.md docs/reference/module-types/container.md docs/reference/module-types/maven-container.md docs/reference/module-types/helm.md docs/reference/module-types/persistentvolumeclaim.md docs/reference/module-types/hadolint.md docs/reference/module-types/README.md docs/reference/module-types/terraform.md docs/reference/module-types/conftest.md docs/reference/module-types/exec.md docs/reference/template-strings.md
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by eysi09** [comment]
Ah yes, this probably because you don't have `parallel` installed which is a tool we run when checking for outdated links. Basically a local dependency. You can get around it by using the `--no-verify` flag when doing `git push`. So something like `git push origin vrybas:fix-docs-typo-f18f32a --no-verify`.

**Comment by eysi09** [comment]
FYI: We're noticing some issues with the docs generation on our end as well. We'll fix that before merging this one.

**Comment by vrybas** [comment]
@eysi09 ok noted. Meanwhile, all checks have passed. Thanks for the advice!

**Comment by edvald** [comment]
That was a lot of back and forth for a single character edit, haha. But yeah we will be fixing this pre-commit hook business :)

**Comment by eysi09** [comment]
Haha yup. We should really get rid of that parallel dependency.

**Pull request merged**
