### PR TITLE
feat(core): lower case username for templates

### PR DESCRIPTION
**Pull request by thsig**
**What this PR does / why we need it**:

In addition to the `local.username` template variable, we now provide `local.usernameLowerCase`.

This is useful e.g. when templating in the local username in namespaces or hostnames.

### CODE REVIEW

**Comment by edvald** [comment]
I'm trying to decide if we consider this a breaking change. It _technically_ is, but it's not particularly likely that this is being used in a manner that expects the prior behavior. @eysi09 what do you think?

**Comment by Chipcius** [comment]
If it is a breaking change, adding a new variable that is lowercase or some modifier that can turn it lowercase would also solve the problem with using the username in namespaces

**Comment by edvald** [comment]
That's actually a good idea. I'd be in favor of adding a `${local.username-lowercase}` or something like that. We have designs on functions/methods on template strings (i.e. modifiers) but that'll take a bit more doing.

**Comment by thsig** [comment]
Good idea—I'll add the lowercase username as a separate variable as you suggest.

**Comment by thsig** [comment]
I've updated the PR—instead of lowercasing `local.username`, I added ` local.usernameLowerCase`.

Does that sound like a decent name for this field?

**Review by edvald — APPROVED** [review]
Looks good, aside from that linting error

**Comment by edvald** [comment]
Also the commit message is now a little odd :)

**Comment by edvald** [comment]
I'll separately work out the failing tests, seems unrelated

**Comment by thsig** [comment]
I've fixed the linting error. Having a hard time coming up with a non-awkward commit message for this one, but I did my best. Haha.

**Pull request merged**
