### PR TITLE
fix OpenFaaS issues

### LINKED ISSUE #298: Failed to pull image when deploying hello-world on Windows
```
PS C:\Users\t480\code\garden\examples\hello-world> garden deploy
Deploy 🚀

× hello-function            → Deploying

Failed deploying service hello-function (from module hello-function). Here is the output:
————————————————————————————————————————————————————————————————————————————————
Error deploying hello-function: Failed - Failed to pull image "hello-function:v4897e03837": rpc error: code = Unknown desc = Error response from daemon: pu
ll access denied for hello-function, repository does not exist or may require 'docker login'
————————————————————————————————————————————————————————————————————————————————

1 deploy task(s) failed!
```

### PR DESCRIPTION
**Pull request by edvald**
Closes #298 and #297 

See individual commits for details

### CODE REVIEW

**Comment by ellenkorbes** [comment]
I tried testing this on Linux and I'm getting the following error:

```
➜  hello-world git:(fix-openfaas-builds) garden build
Build 🔨

✔ hello-npm-package         → Building → Done (took 0 sec)
✔ hello-container           → Building hello-container:v05b43178fc... → Done (took 14.9 sec)
✔ openfaas--builder         → Building openfaas--builder:8d7ae67314... → Done (took 13.7 sec)
✖ hello-function            → Building

Failed building hello-function. Here is the output:
————————————————————————————————————————————————————————————————————————————————
Command failed: docker run -i -v /home/ellen/code/garden/examples/hello-world/.garden/build/hello-function:/wd -v /var/run/docker.sock:/var
/run/docker.sock --workdir /build --net host openfaas--builder:8d7ae67314 faas-cli build -f /wd/stack.yml

Open /wd/stack.yml: no such file or directory

————————————————————————————————————————————————————————————————————————————————

1 build task(s) failed!

See error.log for detailed error message
```

I did re-build, nuke minikube, etc. etc. so I think it's not an issue on my end.

**Comment by edvald** [comment]
Looking into it

**Comment by edvald** [comment]
Side note: Nuking minikube is not necessary when debugging builds. Builds don't rely on the K8s runtime.

**Comment by ellenkorbes** [comment]
And on Windows:

```
PS C:\Users\t480\code\garden\examples\hello-world> garden build
Build 🔨

√ hello-npm-package         → Building → Done (took 0.5 sec)
√ openfaas--builder         → Building openfaas--builder:8d7ae67314... → Done (took 0.6 sec)
√ hello-container           → Building hello-container:v05b43178fc... → Done (took 7.1 sec)
× hello-function            → Building

Failed building hello-function. Here is the output:
————————————————————————————————————————————————————————————————————————————————
Command failed: docker run -i -v C:\Users\t480\code\garden\examples\hello-world\.garden\build\hello-function:/wd -v /var/run/docker.sock:/var/run/docker.sock --workdir /build --net host openfaas--builder:8d7ae6
7314 faas-cli build -f \wd\stack.yml

Open \wd\stack.yml: no such file or directory

————————————————————————————————————————————————————————————————————————————————

1 build task(s) failed!
```

**Comment by eysi09** [comment]
Looks good except when I run `garden delete env` I get:

```
Error validating cleanupEnvironment output from plugin openfaas: key "local-kubernetes" is not allowed at path [local-kubernetes]
```

**Comment by edvald** [comment]
Yep, I'll add a fix for that bug.

**Comment by eysi09** [comment]
Were you planning on putting the fix with this PR? If not I'll go ahead and approve.

**Comment by edvald** [comment]
It's already there (latest commit).

**Comment by eysi09** [comment]
Ah my bad, somehow missed that one.

**Pull request merged**
