### PR TITLE
tool(pulumi): switch default version to 3.122.0

### LINKED ISSUE #6233: Add Pulumi 3.102.0 to fix vulnerability in pulumi deps
* [github.com/cloudflare/circl:v1.3.3/GHSA-9763-4f94-gfch - github.com/cloudflare/circl, github.com/cloudflare/circl and 3 more](https://console.aws.amazon.com/inspector/v2/home?region=us-west-2#/findings?findingArn=arn%3Aaws%3Ainspector2%3Aus-west-2%3A873483817304%3Afinding%2Fcda782f675935cdc850cc0577144e94a)
* [github.com/cloudflare/circl:v1.3.3/GHSA-9763-4f94-gfch - github.com/cloudflare/circl, github.com/cloudflare/circl and 3 more](https://console.aws.amazon.com/inspector/v2/home?region=us-west-2#/findings?findingArn=arn%3Aaws%3Ainspector2%3Aus-west-2%3A873483817304%3Afinding%2F630bf0f4875ebfeae81565098e3d967b)

### PR DESCRIPTION
**Pull request by vvagaytsev**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Patches #6246
Fixes #6233

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by vvagaytsev** [comment]
Default version was not changed in https://github.com/garden-io/garden/pull/6246. This PR fixes that.

**Comment by 10ko** [comment]
Is this a breaking change?

**Comment by vvagaytsev** [comment]
> Is this a breaking change? Theoretically not, since it's just a minor release update, but are we sure there are no breaking changes between 3.70.x and 3.102.x

I'll double check.

**Comment by vvagaytsev** [comment]
@10ko I haven't found any breaking changes in the release notes between 3.70.0 and 3.102.0.

By the way, the latest available version is 3.122.0. Should we update pulumi plugin to use that version?

**Comment by 10ko** [comment]
Yeah, if we are updating better to the latest version

**Comment by vvagaytsev** [comment]
This is ready for review now :)

The default pulumi tool version is now 3.122.0, and it's also used in the Docker image.

**Review by 10ko — APPROVED** [review]

**Pull request merged**
