### PR TITLE
docs: add k8s Deploy action example with shared manifests

### PR DESCRIPTION
**Pull request by eysi09**
**What this PR does / why we need it**:

From the commit message:

This commit adds an example that uses the `kubernetes` deploy action and shares the same manifests between a couple of actions. This is achieved by using Garden template strings in the manifests.

The example is a three tier web app version of the vote example with "web", "API", and "DB" components that I think we should consider using by default.

It's not as complex as the main vote example which tends to draw attention away from the functionality being demonstrated, and not as trivial as the basic "demo-project".

Three tier web apps are also a common pattern that a lot of people will be familiar with.

And lastly, this is also the same example we use in the "How Garden Works" video series so it will become familiar to users eventually.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Added this example following the conversation here: https://github.com/garden-io/garden/issues/4729

We'll also be adding actual docs on the topic, this example is just the first step and can be used as a reference in those docs.

### CODE REVIEW

**Comment by worldofgeese** [comment]
I have now tested this locally to confirm everything runs and is accessible.

I see this as part of a larger initiative to directly address needs in our docs. Currently we suggest the `container` module for a simplified abstract for users. I think there's a space in our docs for positioning this Config Templates example and a Helm library chart example as methods to provide helpful abstractions to downstream (of the Platform Team) consumers.

E.g. a docs page, even a Seed, that walks users through generating shared manifests. This could even be turned into a native `garden` command such as, `garden generate configtemplates` similar to `helm create`.

Your PR mentions,

> - Actions cannot reference files in parent directories. That's why we "hoist" the Garden config for the web and API components to the root (where the manifests reside) and name the config files `api.garden.yml` and `web.garden.yml`.
> - You can also set non primitive values like maps and arrays by
using the `jsonEncode` templating function.

Your first bullet sounds like something we should support in `garden` natively. Do we have a feature request for it? Or any reason why we wouldn't want to implement a feature like this?

For your `jsonEncode` example, could you expand on this with a post-transform example? So users can directly see.

**Review by worldofgeese — COMMENTED** [review]
See comment above 👀

**Comment by eysi09** [comment]
> I see this as part of a larger initiative to directly address needs in our docs

Absolutely, it is. I just started with the examples because they had been requested. But the overall goal is to update the docs and reference the examples from there. 

> Your first bullet sounds like something we should support in garden natively. Do we have a feature request for it? Or any reason why we wouldn't want to implement a feature like this?

Yes, we do but they're stale. My plan was to open a new one with up to date context.

- https://github.com/garden-io/garden/issues/853
- https://github.com/garden-io/garden/issues/1199

I feel quite strongly that we should support this. The current workaround is to hoist everything to the top which is not nice.

> For your jsonEncode example, could you expand on this with a post-transform example? So users can directly see.

Will do.

**Comment by eysi09** [comment]
@worldofgeese, I added a new commit addressing your comments.

**Review by worldofgeese — DISMISSED** [review]
Looks good to me! 🥇

**Review by worldofgeese — APPROVED** [review]
Great shot of clarity and taught me a new key to use for rewriting source path ⚡

**Pull request merged**
