### PR TITLE
Bump Helm to version 3.11.3

### LINKED ISSUE #3753: [FEATURE]: Helm version >= v3.8.0 / Use local helm installation
### Background / Motivation
Garden is currently shipped with Helm v3.7.2. This is problematic for those of us who use OCI registries (eg. Google Artifact Registry).

Can we please upgrade the bundled Helm binary?

We are using Google Artifact Registry for containers and helm charts. In later versions of Helm, its possible to re-use Docker's credential configuration (`gcloud` credential helper) for these registries. Since Garden runs Helm v3.7.2, I'm unable to authenticate via Helm modules. Container modules work fine for the same registry.

### What should the user be able to do?

Users should be able to use Google Artifact Registries for both containers and helm charts, with authentication handled by the `gcloud` credential helper in the local Docker config.

### Why do they want to do this? What problem does it solve?

It allows full usage for Google Artifact Registries for containers and helm charts; providing a private registry with a simple authentication mechanism.

### Suggested Implementation(s)

Bump the bundled Helm binary to v3.11.1

### How important is this feature for you/your team?

🥀 Crucial, Garden is unusable for us without it

### PR DESCRIPTION
**Pull request by chrispsplash**
**What this PR does / why we need it**:

This updates helm-cli spec allowing us to take advantage of crucial new functionality.  For example, the most recent batches of Bitnami charts require OCI support which is not available in 3.7.x.

**Which issue(s) this PR fixes**:

Fixes #3753

**Special notes for your reviewer**:

Starbucks sells a 8oz/250ml size called "short"

### CODE REVIEW

**Comment by edvald** [comment]
I _think_ those test failures may be unrelated to the PR, and the changes seem alright... We'll check quickly before approving+merging.

**Comment by Walther** [comment]
Thank you for making this PR!
We have now completed our major effort of Garden Bonsai 0.13 release, and our long-lived `0.13` branch has finally been merged to `main`.
Could you please update this PR with the latest `main` (either with a merge or a rebase), and let's verify everything important passes in our newest CI configuration. Thanks!

**Comment by stefreak** [comment]
Helm has been bumped to 3.12.0 in #4491

This will also be backported to 0.12

**Comment by vvagaytsev** [comment]
Back-ported to `0.12` in #4493.

**Pull request closed without merging**
