### PR TITLE
Update external gateway URL by option

### PR DESCRIPTION
**Pull request by pbaezab**
Add config gateway url by default and overwrite generate url when exist.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by pbaezab** [comment]
Add comments @eysi09 and @alexellis

**Comment by pbaezab** [comment]
Failed with microk8s:

`Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
`

**Comment by alexellis** [comment]
I see I got a ping but I'm not sure what I can do here, so I'll leave it to the team.

Thanks for using openfaas.

**Comment by eysi09** [comment]
Assigning this to @edvald who's done most the work on the `openfaas` provider. Here's the original issue for context: #1758

**Comment by edvald** [comment]
Closing in favor of #1765 (which has been approved)

**Pull request closed without merging**
