### PR TITLE
feat(terraform): add terraform 1.3.7

### PR DESCRIPTION
**Pull request by stefreak**
**What this PR does / why we need it**:
- feat(terraform): add terraform 1.3.7
- test(terraform): run tests for multiple tf versions

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by stefreak** [comment]
The tests will pass once #3632 has been merged

**Comment by stefreak** [comment]
The tests for select workspace fail for some reason, unexpectedly

**Comment by vvagaytsev** [comment]
@stefreak @Walther should we close this in favor of #4293?

**Comment by Walther** [comment]
Closing this as https://github.com/garden-io/garden/pull/4293 has been merged instead

**Comment by stefreak** [comment]
@vvagaytsev @Walther The reason this wasn't merged yet is that the tests fail, if actually using the latest terraform version in the tests (it was hardcoded to the oldest terraform version that we support)

**Comment by stefreak** [comment]
Opened #4381 with the test change.

**Pull request closed without merging**
