### PR TITLE
chore(deps): update semver, commitlint, google kms

### PR DESCRIPTION
**Pull request by Walther**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

This _should_ fix these two Dependabot alerts, but we'll know for sure only after merging.

- https://github.com/garden-io/garden/security/dependabot/913
- https://github.com/garden-io/garden/security/dependabot/868

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Walther** [comment]
`e2e-vote` seems to be broken on other PRs as well, unrelated to this PR.

**Review by vvagaytsev — APPROVED** [review]
Thanks! 💯

**Comment by Walther** [comment]
Forgot to mention in the description: the google kms library was bumped by two major versions, but the only breaking changes are to the underlying Node version support - we are unaffected.

**Comment by shumailxyz** [comment]
@Walther Thanks for taking care of these 💯

**Pull request merged**
