### PR TITLE
chore(examples): use local.demo.garden for local kubernetes examples

### PR DESCRIPTION
**Pull request by twelvemo**
**What this PR does / why we need it**:
Use local.demo.garden domain for local examples instead of local.app.garden.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Walther — APPROVED** [review]
Thank you! 🎉 
Verified locally with `for example in $(ls -1); do pushd $example; echo $example; gdev deploy && gdev test && gdev delete env; popd; done;` and checking that all examples have ingress controllers referring the url `local.demo.garden`. (There were some failures in some examples, but they were completely unrelated to this PR.)

**Comment by Walther** [comment]
We should also port this to the `0.13` branch

**Comment by vvagaytsev** [comment]
> We should also port this to the `0.13` branch

Sure! Also, we have to update the rest examples to use the new domain. That can be addressed in a separate PR.

**Review by vvagaytsev — APPROVED** [review]
Thank you! 🚀

**Pull request merged**
