### PR TITLE
chore: port "upgrade node version to 16" to 0.13

### PR DESCRIPTION
**Pull request by Walther**
**What this PR does / why we need it**:

Ports https://github.com/garden-io/garden/pull/3305 to the `0.13` branch

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by edvald** [comment]
Looks like one or more packages need updating. I like to use this thing: https://www.npmjs.com/package/npm-check-updates

**Comment by Walther** [comment]
@edvald yes indeed, we're behind on a lot of packages. my original plan was to get the 16 upgrade out of the way as soon as possible as it affects things more broadly (CI base images etc) and then do dependency updates in a separate pass (except the ones that were *required* to be updated to work on 16)

**Comment by Walther** [comment]
This should now work, tested with
```
rm -rf node_modules
fnm use # or nvm use
yarn
yarn dev
cd examples/demo-project
gdev validate
gdev deploy
```

**Review by vvagaytsev — APPROVED** [review]
LGTM! 🚀 Thank you!

**Pull request merged**
