### PR TITLE
refactor: remove deprecated providers config

### PR DESCRIPTION
**Pull request by vvagaytsev**
**What this PR does / why we need it**:
BREAKING CHANGE

The old field `environments[].providers[]` is no longer supported in the project configuration.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Orzelius — CHANGES_REQUESTED** [review]
There are still a few examples and test projects left that use the old api. Search for `^  providers` and you'll find 'em

**Comment by vvagaytsev** [comment]
> There are still a few examples and test projects left that use the old api. Search for `^ providers` and you'll find 'em

Yes, I know. There is only one project left -- it is https://github.com/garden-io/garden/blob/master/core/test/data/test-projects/v10-configs/garden.yml. It's used in https://github.com/garden-io/garden/blob/master/core/test/unit/src/commands/migrate.ts to test the migrations from the older Garden versions. So, I left it without changes. Migration tests do not cause any config schema validation failures.

**Comment by Orzelius** [comment]
There are also some docs and examples that use that

**Comment by vvagaytsev** [comment]
@Orzelius the examples and guides have been fixed in https://github.com/garden-io/garden/pull/3103/commits/3258356e5212ce2c07c508a9f8f4bc034bb0e4cb.

**Review by Orzelius — APPROVED** [review]

**Pull request merged**
