### PR TITLE
0.13: fix all integ tests

### PR DESCRIPTION
**Pull request by Orzelius**
### ₍꒢  ̣̮꒢₎

We can actually close this once merged https://github.com/garden-io/garden/issues/3113

Probably need to open a separate issue for all the tests skipped or the ones yet to be written.

### CODE REVIEW

**Comment by Orzelius** [comment]
I went with the one integ test vm approach as I didn't feel like debugging and looking into issues that came up when enabling all of them.

You can take a look at [this ci run](https://app.circleci.com/pipelines/github/garden-io/garden/15914/workflows/4244a715-9b31-4f84-bd59-93ec3ad58899) and judge for yourself.

**Comment by Walther** [comment]
Looking at the VM tests, I wonder if the errors are related to the known issue of being unable to switch between 0.12 and 0.13 garden cli version when working on the same kubernetes target, without deleting (and re-deploying) the `garden-system` namespace in between
```
The Deployment "simple-service" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"service":"simple-service"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Review by Walther — APPROVED** [review]
good job! 🎉 🚀 
let's get this merged to unblock the other PRs and do the follow-up tasks later

**Comment by Orzelius** [comment]
okidoki, merging

**Pull request merged**
