### PR TITLE
feat(core): render module command

### PR DESCRIPTION
**Pull request by thsig**
**What this PR does / why we need it**:

Added a new command: `garden render module`.

This command resolves all template strings in the module, and outputs the full module configuration (which includes the resolved module version).

This is useful for debugging/writing template strings for modules, and for reasoning about which files/variables factor into the  module's version calculation.

Note: Garden Cloud/Enterprise secrets are filtered from the rendered output.

### CODE REVIEW

**Comment by thsig** [comment]
@eysi09 @edvald: What do we think about the fields included in the output here?

I thought it made sense to omit `serviceConfigs`, `testConfigs` and `taskConfigs`, since the services/tests/tasks also appear in `module.spec`.

**Comment by tedchang77** [comment]
@thsig we were going to make a request for this very feature to help us with debugging...  this command would be combining the functionality of the garden get modules and the garden get config command, correct?

**Comment by edvald** [comment]
@thsig I think we should fold this into the `get modules` command, and basically make the visual output there nicer. The planned `garden render` commands will have different semantics and this clashes with those plans.

**Comment by thsig** [comment]
Yeah, agreed.

**Comment by thsig** [comment]
Closing in favor of #2982.

**Pull request closed without merging**
