### PR TITLE
fix(k8s): wait for Tiller pod to be ready when initializing

### LINKED ISSUE #228: Helm needs to wait for Tiller pod
When running things for the first time, I get this error message:

```
➜  hello-world git:(quick-fix) ✗ garden deploy
Deploy 🚀

✔ local-kubernetes   → Configured
  openfaas           → Configuring...
✔ openfaas-system    → Preparing chart... → Done (took 2.1 sec)
  openfaas-system    → Deploying

Failed deploying service openfaas-system (from module openfaas-system). Here is the output:
————————————————————————————————————————————————————————————————————————————————
Command failed: helm --kube-context minikube install /home/ellen/code/garden/garden-cli/static/openfaas/system/.garden/build/openfaas-system/openfaas --name garden--garden-openfaas-
system--openfaas-system --namespace garden--hello--hello-world--openfaas --values /home/ellen/code/garden/garden-cli/static/openfaas/system/.garden/build/openfaas-system/openfaas/ga
rden-values.yml --wait
Error: could not find a ready tiller pod


————————————————————————————————————————————————————————————————————————————————

local-kubernetes: 1 errors occurred when configuring environment
```

According to @edvald:

> If I'm not mistaken, this should work on a second attempt. If it's the same issue I bumped into, it's that Helm doesn't wait for the tiller pod to be ready. We need to add a wait call when setting it up.

### PR DESCRIPTION
**Pull request by edvald**
Fixes #228

### CODE REVIEW

**Comment by edvald** [comment]
FYI @ellenkorbes

**Comment by ellenkorbes** [comment]
```
➜  hello-world git:(master) git pull
remote: Counting objects: 115, done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 115 (delta 72), reused 114 (delta 72), pack-reused 0
Receiving objects: 100% (115/115), 20.46 KiB | 5.11 MiB/s, done.
Resolving deltas: 100% (72/72), completed with 53 local objects.
From github.com:garden-io/garden
   877a74c..1dc936e  master              -> origin/master
   02708b1..9200a66  templating-refactor -> origin/templating-refactor
 * [new branch]      tiller-wait         -> origin/tiller-wait
 * [new branch]      tls-pt1             -> origin/tls-pt1
Updating 877a74c..1dc936e
Fast-forward
 examples/hello-world/services/hello-container/test/integ.js | 2 +-
 garden-cli/static/openfaas/openfaas-builder/bootstrap.sh    | 6 +++---
 garden-cli/test/integ/run                                   | 3 ++-
 3 files changed, 6 insertions(+), 5 deletions(-)
➜  hello-world git:(master) git checkout tiller-wait
Branch 'tiller-wait' set up to track remote branch 'tiller-wait' from 'origin'.
Switched to a new branch 'tiller-wait'
➜  hello-world git:(tiller-wait) minikube stop
Stopping local Kubernetes cluster...
Machine stopped.
➜  hello-world git:(tiller-wait) minikube delete
Deleting local Kubernetes cluster...
Machine deleted.
➜  hello-world git:(tiller-wait) minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
➜  hello-world git:(tiller-wait) garden build
Build 🔨

✔ hello-npm-package  → Building → Done (took 0 sec)
✔ openfaas--openf... → Building → Done (took 24.5 sec)
✔ hello-container    → Building hello-container:v2714140750... → Done (took 38.4 sec)
✔ hello-function     → Building → Done (took 53 sec)

Done! ✔️

➜  hello-world git:(tiller-wait) garden deploy
Deploy 🚀

✔ local-kubernetes   → Configured
  openfaas           → Configuring...
✔ openfaas-system    → Preparing chart... → Done (took 1.7 sec)
  openfaas-system    → Deploying

Failed deploying service openfaas-system (from module openfaas-system). Here is the output:
————————————————————————————————————————————————————————————————————————————————
Command failed: helm --kube-context minikube install /home/ellen/code/garden/garden-cli/static/openfaas/system/.garden/build/openfaas-system/openfaas --name garden--garden-openfaas-
system--openfaas-system --namespace garden--hello--hello-world--openfaas --values /home/ellen/code/garden/garden-cli/static/openfaas/system/.garden/build/openfaas-system/openfaas/ga
rden-values.yml --wait
Error: could not find a ready tiller pod


————————————————————————————————————————————————————————————————————————————————

local-kubernetes: 1 errors occurred when configuring environment

See error.log for detailed error message
➜  hello-world git:(tiller-wait) 
```
🤔

**Comment by edvald** [comment]
Hrmm. Could you post your helm version, and maybe try updating it? When looking for a solution I came across a merged PR to fix the `--wait` flag.

**Comment by edvald** [comment]
It supposedly got fixed in helm 2.8.2: https://github.com/helm/helm/issues/3393

I tried it on my side and it seems to work as expected, will have to investigate further if this doesn't do the trick.

**Comment by edvald** [comment]
Hrmm. Maybe you could try the init command manually?
`helm init --wait --service-account default --upgrade`

**Comment by ellenkorbes** [comment]
That works 🤔

**Comment by edvald** [comment]
That's odd. Just to be clear, this is only an issue when doing the initial deploy, right?

**Comment by edvald** [comment]
I have a theory - we're not specifying the `--kube-context` parameter in the init command, and your default context may be different. So that would cause helm to be initializing against some other cluster. Is that a possible explanation? We should fix that either way, so I'll update the PR.

**Comment by ellenkorbes** [comment]
> this is only an issue when doing the initial deploy, right?
Yes.

> So that would cause helm to be initializing against some other cluster. Is that a possible explanation?
No, that's the only cluster.

Things as working as of the last commit. Let's merge this.

**Pull request merged**
