### PR TITLE
docs(pulumi): re-generated reference docs

### PR DESCRIPTION
**Pull request by vvagaytsev**
**What this PR does / why we need it**:
Patches #3400

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by stefreak — CHANGES_REQUESTED** [review]
I think we should also revert `_includeInGardenImage: false` right?
Do we want to continue to include pulumi in our workflow runner docker images?

**Comment by vvagaytsev** [comment]
> I think we should also revert `_includeInGardenImage: false` right? Do we want to continue to include pulumi in our workflow runner docker images?

I'm not 100% sure. It looks like we have had `_includeInGardenImage: false` for every default Pulumi version, buy mabe we don't need to include it in workflow runner images.

@thsig wdyt?

**Comment by thsig** [comment]
I don't think we need to include it.

We can always change our mind later and start including the latest version.

**Review by stefreak — APPROVED** [review]
ok then LGTM 🚢 👍

**Comment by stefreak** [comment]
> In #3400 we got `_includeInGardenImage: false` for Pulumi `3.40.0` because it stopped being the latest version. And we got `_includeInGardenImage: true` for Pulumi `3.48.0` because it became the latest one.
> 
> So, it should not make any harm. We can keep it as it is, and exclude it in a separate PR.

Ah right, got it! My fault I didn't look at the diff closely enough. Thanks for clarifying!

**Pull request merged**
