### PR TITLE
docs: fix action reference docs

### PR DESCRIPTION
**Pull request by Orzelius**
action kind docs were missing readmes which are used for gitbook and
table of content generation

closes https://github.com/garden-io/garden/issues/4602

### CODE REVIEW

**Review by Walther — APPROVED** [review]
Thanks for the fix ✨ 

_(Would be nice if we could some day have previews for docs PRs to double check that everything will work - now we just have to trust it works and create another PR later in case there's an issue)_

**Comment by eysi09** [comment]
> Thanks for the fix ✨
> 
> _(Would be nice if we could some day have previews for docs PRs to double check that everything will work - now we just have to trust it works and create another PR later in case there's an issue)_

We should. It's a Gitbook feature. 

Perhaps @Orzelius can look into that since you have access.

**Comment by eysi09** [comment]
Oh wait, here it is. Does the link work for you?

Screenshot 2023-06-14 at 18 44 35

**Comment by eysi09** [comment]
Ok gotcha, let’s look into that

**Pull request merged**
