### PR TITLE
docs: centralize `contributor` docs and provide on-ramp

### PR DESCRIPTION
**Pull request by worldofgeese**
To reduce docs sprawl and provide a more discoverable on-ramp for internal and external contributors to Garden, I've broken out and centralized contributor docs under `docs`.

This includes a complete Contributing to the Docs page intended to help guide new external and internal contributors to our documentation who may or may not be Git-adept. It is also intended to serve as supporting documentation for any technical writer role we may onboard in the future.

- [x] Add recommendation to use a Markdown linter

### CODE REVIEW

**Review by eysi09 — APPROVED** [review]

**Comment by eysi09** [comment]
This is great. Thanks!

**Comment by eysi09** [comment]
@worldofgeese, can we resolve the conflicts and get this merged?

I have a "doc on docs" that I'd like to add there.

**Comment by worldofgeese** [comment]
@eysi09 thanks for checking in on this: @valeriegarden and I are testing them now. I'll pull her feedback in to this then flag you.

**Comment by worldofgeese** [comment]
@eysi09 Val and I got through some Git fundamentals yesterday but not enough to validate these docs. Let's just merge these when they're ready and we can make a new PR for any suggestions she has in the future.

**Comment by worldofgeese** [comment]
Some docs checks are failing. Will re-generate and test again.

**Comment by eysi09** [comment]
> @eysi09 Val and I got through some Git fundamentals yesterday but not enough to validate these docs. Let's just merge these when they're ready and we can make a new PR for any suggestions she has in the future.

Sounds good!

**Review by eysi09 — DISMISSED** [review]

**Comment by eysi09** [comment]
Looks like there's a flaky framework test in there: https://github.com/garden-io/garden/blob/main/core/test/unit/src/commands/self-update.ts#L306

**Comment by worldofgeese** [comment]
@eysi09 I hadn't run `generate-docs`. Rebased my work to tip of `main`, generated the ToC and pushed. It *should* be fixed now but let's see. 👀

**Comment by worldofgeese** [comment]
@eysi09 sorry about the back and forth! I'll wait to ping you until I've gotten checks back next time. We are finally ready to merge!

**Comment by eysi09** [comment]
> @eysi09 sorry about the back and forth! I'll wait to ping you until I've gotten checks back next time. We are finally ready to merge!

No worries! Thanks for wrapping this up 🙏

**Review by eysi09 — APPROVED** [review]

**Pull request merged**
