### PR TITLE
fix(kubernetes): do not fail to deploy List kinds (e.g. ConfigMapList)

### LINKED ISSUE #4500: 0.13: [Bug]: kind=Deploy type=kubernetes fails with `kind: ConfigMapList`
## Garden Bonsai (0.13) Bug
kubernetes Deploys fail with kubernetes manifests of type `kind: ConfigMapList`.

### Current Behavior
```
✖ deploy.test          → Failed processing Deploy type=kubernetes name=test (took 0.58 sec). Here is the output:

────────────────────────────────────────────────────────────────────────────────
Command "/Users/steffen/.garden/tools/kubectl/f8a39834529cd1ed/kubectl --context=docker-desktop apply --output=json -f -" failed with code 1:

error: error validating "STDIN": error validating data: [ValidationError(ConfigMapList.metadata): unknown field "annotations" in io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta, ValidationError(ConfigMapList.metadata): unknown field "labels" in io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta]; if you choose to ignore these errors, turn validation off with --validate=false

error: error validating "STDIN": error validating data: [ValidationError(ConfigMapList.metadata): unknown field "annotations" in io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta, ValidationError(ConfigMapList.metadata): unknown field "labels" in io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta]; if you choose to ignore these errors, turn validation off with --validate=false
────────────────────────────────────────────────────────────────────────────────
1 deploy action(s) failed!
```

### Expected behavior

Deploy succeeded

### Reproducible example

```
kind: Project
apiVersion: garden.io/v1
name: repro
environments:
 - name: default
providers:
 - name: local-kubernetes

---

kind: Deploy
type: kubernetes
name: test
source:
  repository:
    url: https://github.com/prometheus-operator/kube-prometheus.git#0198f98f682f1d7e40b1dd5615437a916107f1aa
spec:
  namespace: monitoring
  files:
    - manifests/grafana-dashboardDefinitions.yaml
```

### Workaround

Do not use `ConfigMapList` but use separete yaml documents with `ConfigMap` objects.

### Suggested solution(s)

Something like this could do the trick:

```
diff --git a/core/src/plugins/kubernetes/kubectl.ts b/core/src/plugins/kubernetes/kubectl.ts
index d15444f4d..05f380d51 100644
--- a/core/src/plugins/kubernetes/kubectl.ts
+++ b/core/src/plugins/kubernetes/kubectl.ts
@@ -71,13 +71,13 @@ export async function apply({
   // because kubectl applies some normalization/transformation that is sometimes difficult to reason about).
   // Hashing the input prevents "Too long annotation..." errors.
   for (const manifest of manifests) {
-    if (!manifest.metadata.annotations) {
-      manifest.metadata.annotations = {}
-    }
-    if (manifest.metadata.annotations[gardenAnnotationKey("manifest-hash")]) {
-      delete manifest.metadata.annotations[gardenAnnotationKey("manifest-hash")]
+    if (manifest.kind === "ConfigMapList") {
+      for (const configMap of manifest.items as KubernetesResource[]) {
+        await annotateResource(configMap)
+      }
+    } else {
+      await annotateResource(manifest)
     }
-    manifest.metadata.annotations[gardenAnnotationKey("manifest-hash")] = await hashManifest(manifest)
   }

   // The `--prune` option for `kubectl apply` currently isn't backwards-compatible, so here, we essentially
@@ -326,3 +326,13 @@ export const kubectlSpec: PluginToolSpec = {
     },
   ],
 }
+
+async function annotateResource(manifest: KubernetesResource) {
+  if (!manifest.metadata.annotations) {
+    manifest.metadata.annotations = {}
+  }
+  if (manifest.metadata.annotations[gardenAnnotationKey("manifest-hash")]) {
+    delete manifest.metadata.annotations[gardenAnnotationKey("manifest-hash")]
+  }
+  manifest.metadata.annotations[gardenAnnotationKey("manifest-hash")] = await hashManifest(manifest)
+}
```

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** Docker desktop

`garden version`

### PR DESCRIPTION
**Pull request by stefreak**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4500

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Orzelius — DISMISSED** [review]
Thanks for figuring this out!

**Review by Walther — APPROVED** [review]
🎉

**Comment by stefreak** [comment]
@Orzelius @Walther @edvald I wonder if this would break if there was a custom resource definition with custom resources ending with `*List`. This code would fail then. Maybe it would be better to hardcode a list of specific kinds of resources instead of just looking for the `*List` ending. What do you think?

**Comment by stefreak** [comment]
Maybe it would be safe enough to only flatMap the List if it actually has `items`– and otherwise keep it as-is

**Comment by edvald** [comment]
I think we should only do this for resources with `apiVersion: v1`, and make sure we gracefully fail on invalid resources. If we do that, it should be all good.

**Comment by stefreak** [comment]
[Kustomize also treats](https://github.com/kubernetes-sigs/kustomize/blob/cf3e81b590ab1fd7fc8f50849535f44bfea0d355/api/resource/factory.go#L550) anything with `*List` as a List, and errors if items is not a list. So I guess this is ok for now.

**Review by Orzelius — APPROVED** [review]

**Comment by edvald** [comment]
I still think we should only do this for core API resources, basically just `apiVersion: v1`. Otherwise this may break some CRDs that can be named "SomethingList" and have completely unrelated semantics.

**Pull request merged**
