### PR TITLE
fix(k8s): ensure rendered helm chart contain runtime values [WIP]

### LINKED ISSUE #1795: Garden fails to find helm deployed resources where apiVersions don't match
### Current Behavior

I've got a helm module that has an ingress.  The ingress says:

```
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
```

My cluster runs Kubernetes 1.13, so `helm install` ends up rendering this as:
```yaml
apiVersion: extensions/v1beta1
```

When I run `garden dev`, garden gets stuck on this:
```
⠼ frontend                  → Deploying version v-fe774671a4...
   ℹ frontend                  → Waiting for resources to be ready...
```

Bumping log level to 4, it turns out that garden is failing to find the ingress resource:

```
Status of Ingress frontend is "missing"                                                                                                                                   
    Kubernetes: Getting API resource info for group networking.k8s.io/v1beta1                                                                                                 
    Status of ConfigMap frontend is "ready"                                                                                                                                   
    Status of Service frontend is "ready"                                                                                                                                     
    Status of Deployment frontend is "ready"                                                                                                                                  
    Status of Ingress frontend is "missing"                                                                                                                                   
    Kubernetes: Getting API resource info for group networking.k8s.io/v1beta1                                                                                                 
    Status of ConfigMap frontend is "ready"                                                                                                                                   
    Status of Service frontend is "ready"                                                                                                                                     
    Status of Deployment frontend is "ready"                                                                                                                                  
    Status of Ingress frontend is "missing"                                                                                                                                   
    Kubernetes: Getting API resource info for group networking.k8s.io/v1beta1                                                                                                 
    Status of ConfigMap frontend is "ready"                                                                                                                                   
    Status of Service frontend is "ready"                                                                                                                                     
    Status of Deployment frontend is "ready"                                                                                                                                  
    Status of Ingress frontend is "missing"
```

### Expected behavior

Garden is able to find the ingress resource.

### Workaround

Remove the conditional from the ingress template :(

### Suggested solution(s)

It appears that garden uses `helm render` under the hood, which unfortunately renders the ingress template as:

```yaml
apiVersion: extensions/v1beta1
```

In other words, it apparently does not take into account the cluster's kubernetes version.  Perhaps `.Capabilities.KubeVersion.GitVersion` does not have a value when `helm render` is run.

It turns out though that `helm install --dry-run` renders the template as we'd expect, i.e. it *does* take into account the actual cluster's version.

So it seems garden can use `helm install --dry-run` instead of `helm render` to get an accurate rendering.

### Your environment
```
▶ garden --version
0.11.12
```

### PR DESCRIPTION
**Pull request by eysi09**
**What this PR does / why we need it**:

The `helm template` command doesn't render values that need to be
retrieved from the cluster. We therefore use `helm install|upgrade
--dry-run` instead.

**Which issue(s) this PR fixes**:

Fixes #1795 

**Special notes for your reviewer**:

N/A

### CODE REVIEW

**Comment by eysi09** [comment]
Not quite sure why this is failing, and especially why it's not failing consistently.

**Comment by edvald** [comment]
@eysi09 it does appear to be failing consistently, on the same test. Perhaps something to do with how the output from the `helm install` command differs from the `helm template` command?

**Comment by eysi09** [comment]
This is after making some changes that broke all the things. Before, it only failed for K8s version 1.15 and up (IIRC). And yes, it did fail consistently for those. (In case you were looking at the CI results after making the change).

**Comment by edvald** [comment]
Closing in favor of a slightly different approach (I'll build off this branch but make some further changes).

**Pull request closed without merging**
