### PR TITLE
chore(examples): create a modules-to-actions example

### PR DESCRIPTION
**Pull request by Walther**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/garden-io/garden/issues/3804, although the scope has changed.

**Special notes for your reviewer**:
Will be squashed before merging.

### CODE REVIEW

**Comment by edvald** [comment]
I'm sort of thinking this example is redundant now. When it was made, being able to put several modules in one file was a new feature, but it's so basic at this point I think it feels unnecessary :P

**Comment by Orzelius** [comment]
The feature might be obvious to us but newcomers might not think of it.

Also, we should have an example with module and document how they get converted to actions and what limits and problems users might face if they stick with modules. This example could serve that purpose.

**Comment by edvald** [comment]
Sure, I could go with that. In that case I'd suggest renaming the project (I don't know... `legacy-modules`?) and updating the docs accordingly.

**Review by vvagaytsev — APPROVED** [review]
Looks good! Thank you! 👍

**Pull request merged**
