### PR TITLE
chore(examples): update vote example to use action configs

### PR DESCRIPTION
**Pull request by Walther**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/garden-io/garden/issues/3757

**Special notes for your reviewer**:

Second example I'm converting, please let me know if there's anything I've missed or if anything can be made more idiomatic!

### CODE REVIEW

**Comment by edvald** [comment]
Looks good. Could you uncomment the test from the CI config? For the examples that we e2e test we should re-enable the tests as we move through them.

**Comment by edvald** [comment]
Looks good. Could you uncomment the test from the CI config? For the examples that we e2e test we should re-enable the tests as we move through them.

**Review by Orzelius — APPROVED** [review]
Looks good, but I didn't try the changes out so I'm trusting you did.

**Review by vvagaytsev — APPROVED** [review]
👍 👍 👍

**Pull request merged**
