### PR TITLE
docs: Fix dead link and minor edits on quickstart guide

### PR DESCRIPTION
**Pull request by highb**
**What this PR does / why we need it**:

Fixes a dead link from the quickstart guide to the installation guide. A few small grammatical/wording changes to the quickstart guide.

**Special notes for your reviewer**:

### CODE REVIEW

**Review by eysi09 — DISMISSED** [review]
Looks good to me ✨

Thanks so much for the contribution @highb!

**Comment by stefreak** [comment]
@highb the head branch needs to be `garden-io:main` and not `garden-io:latest-release`.
Changing the head branch also requires rebasing your commits, and I can't push into your fork. Can you do those two things?
Thank you 🙏

**Review by stefreak — CHANGES_REQUESTED** [review]
Target branch for the pull request must be `garden-io:main`.

**Comment by highb** [comment]
I don't feel like re-basing and dealing with the conflicts, so I'm going to close this.

**Pull request closed without merging**
