### PR TITLE
improvement(dashboard): add path field to each module in overview page

### PR DESCRIPTION
**Pull request by benstov**
While adding the path field i noticed the structure wasn't fully clear, so i aligned the Fields > Field > Key/Value throughout all of the Module component

See updated screenshots below in the comments

### CODE REVIEW

**Comment by edvald** [comment]
This feels a little visually noisy to me. Could you maybe try reducing the font size for the path and making it a lighter grey? Also, did you check how this comes out with modules contained in remote sources?

**Comment by benstov** [comment]
> This feels a little visually noisy to me. Could you maybe try reducing the font size for the path and making it a lighter grey? Also, did you check how this comes out with modules contained in remote sources?

i

**Comment by benstov** [comment]
> This feels a little visually noisy to me. Could you maybe try reducing the font size for the path and making it a lighter grey?

Screenshot 2019-06-06 at 14 12 50

**Comment by 10ko** [comment]
Hi Ben,
Thanks for the PR.
I have few comments:
 - The path has `cursor: pointer` and it's a bit misleading, since it's not a link. It's also difficult to select for some reason.
 - There seems to be a regression on the description field: we cut the word between lines when it doesn't fit (see jworker below) 
Screenshot 2019-06-06 at 15 07 20
 - Not sure if that's necessary but [this few lines](https://github.com/garden-io/garden/blob/785f97fd04f26ed47763893aab9bdb0a870e26eb/dashboard/src/components/entity-card.tsx#L112-L116) have some confusing naming? 
  ```typescript
        {state && (
              {state}
          <State state={state}>
            </State>
            {state}
          )}
          </State>
```

**Pull request closed without merging**
