### PR TITLE
improvement: upgraded default terraform tool version to 1.2.9

### LINKED ISSUE #3209: [FEATURE]: Add terraform version 1.2.9 to tools
### Background / Motivation

Trying to upgrade to the latest terraform version

### What should the user be able to do?

Use terraform version 1.2.9

### PR DESCRIPTION
**Pull request by stefreak**
**What this PR does / why we need it**:

Add latest stable terraform release to our selection of tools.

**BREAKING CHANGE**: Change default terraform version from `0.13.3` to `1.2.9`

**Which issue(s) this PR fixes**:

Fixes #3209

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by stefreak** [comment]
Verified that we are compatible with 1.2.9 by updating our internal garden cloud terraform to 1.2.9 and running `plugins terraform plan-root`

**Comment by vvagaytsev** [comment]
Looks good, but the default version was changed: `0.13.3 -> 1.2.9`. I'm not that familiar with Terraform. Can it be a breaking change for any scenarios? Are there any incompatible changes between `0.x` and `1.x`?

**Review by vvagaytsev — APPROVED** [review]
LGTM, I'd suggest to change the commit message to "improvement: upgraded default terraform tool version to `1.2.9`"

**Comment by stefreak** [comment]
@vvagaytsev there are probably breaking changes in the terraform code itself, but the CLI interface should be fairly stable.

I still added a BREAKING CHANGE warning in the commit message, I think the changelog tool should extract that later

**Pull request merged**
